### PR TITLE
Added support for skipping children

### PR DESCRIPTION
**Pull request by regexident**
This is particularly useful for avoiding greedy visiting when only a shallow parse is needed, e.g. to obtain method signatures, while skipping the methods' bodies.

I chose to pass a `skip_children: &mut bool` (with default value `false`), rather than adding an `enum Children { Skip, Visit }` and having `fn visit_*` return `-> Children` (or whatever a better name would be), as the former allows for ignoring (for non-skipping semantics), while the latter would require a `Default::default()` as the last line of every overridden method regardless.

With `_semantics: &Semantics` [removed](https://github.com/pksunkara/cargo-up/pull/2#issuecomment-702962389) the method signatures should be fairly clean again.

(Marking this as "draft" for now as it will result in a merge conflict. I'll do a manual rebase when it's time.)

### CODE REVIEW

**Comment by pksunkara** [comment]
Do you think we can use some kind of DI and make `SkipChildren` trait or something like that? I am trying to see if we can support both `visit_method_expr(self, node)` and `visit_method_expr(self, node, any_arg)` while also allowing the user to customise the behaviour.

I might just be rambling.

**Comment by pksunkara** [comment]
On second thought, let's go ahead with your PR. I thought about returning `bool`, but as you said, it wouldn't look good when we want to ignore.

But I would much rather create `Options { skip_children: bool }` and use `options: &mut Options` as the third param. This way it is more flexible for future improvement. What do you think?

**Comment by regexident** [comment]
`Options` is definitely more flexible, yes!

**Comment by pksunkara** [comment]
I did this since I had some time today, hope you don't mind. I released 0.2.0 on crates.io. Hopefully, your refactor is working well. Ping me if you need anything else.

**Pull request closed without merging**
